l_russian:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 group_armor_title: "Танковые батальоны"
 HAS_ARMIES_WITH_OLD_TEMPLATE: "§RЭтот шаблон нельзя удалить, потому что есть дивизии ($AMOUNT|H$), которые меняют этот шаблон на новый (они ожидают технику, соответствующую новому шаблону).§!"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC: "У группировки должен быть хотя бы один приказ на ТВД, закрепленный за любой группой."

#fixed missing article
 CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§GЩелкните§!, чтобы указать точку развертывания для этой группировки.\n§GПравый щелчок§! - отменить точку.\n§YЭто - шаблон колоний, его можно развертывать только в своей стране!§!"
