l_russian:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 group_armor_title: "Бронетанковые батальоны"
 HAS_ARMIES_WITH_OLD_TEMPLATE: "§RНевозможно удалить этот шаблон, так как $AMOUNT|H$ дивизия(-ий) переходит(-ят) с этого шаблона на новый (ожидает получения снаряжения по новому шаблону).§!"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC: "Для назначения в любую группу развёртывание должно иметь хотя бы один приказ в театре военных действий."

#fixed missing article
 CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§GНажмите§!, чтобы установить место развёртывания.\n§GЩёлкните ПКМ§!, чтобы сбросить местоположение.\n§YЭто колониальный шаблон, его можно развернуть только в стране происхождения!§!"
