l_russian:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 PRODUCTION_MATERIALS_ALUMINIUM: "Алюминий"
 PRODUCTION_VEHICLES_BUTTON: "Производить бронетехнику"
 PRODUCTION_VEHICLES_BUTTON_DISABLED: "Бронетехника §Rне изобретена§!!"
 PRODUCTION_ARMOR_FILTER: "Бронетехника"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE: "§HЛицензионное производство§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL: "§HВыпуск фабрик по лицензии§!\nИтого: $VALUE|+%$\nДетализация:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION: "§YРазница в технологиях по лицензии§!:\n Базовое: $BASE|+%$\n Итоговое с модификаторами: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER: "§YМодификатор лицензии§!:\n Базовое: $BASE|+%$\n Итоговое с модификаторами: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION: "§YНе в одном альянсе с лицензиаром§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE: "§YНет активной лицензии§!: $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST: "§YСтоимость лицензии§!: £civ_factory $AMOUNT|Y$"
