l_russian:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 PRODUCTION_MATERIALS_ALUMINIUM: "Алюминий"
 PRODUCTION_VEHICLES_BUTTON: "Производство бронетехники"
 PRODUCTION_VEHICLES_BUTTON_DISABLED: "Бронетехника §Rне изобретена§!!"
 PRODUCTION_ARMOR_FILTER: "Бронетехника"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE: "§HЛицензированное производство§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL: "§HОбъем заводского производства по лицензии§!\nВсего: $VALUE|+%$\nРазбивка:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION: "§YРазница между лицензированной технологией§!:\n Базовое значение: $BASE|+%$\n Итоговое значение: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER: "§YКоэффициент лицензии§!:\n Базовое значение: $BASE|+%$\n Итоговое значение: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION: "§YНе в альянсе с лицензиаром§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE: "§YНет действующей лицензии§!: $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST: "§YСтоимость лицензии§!: £civ_factory $AMOUNT|Y$"
