l_russian:
 ######################################################## 
 ### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ### 
 ######################################################## 
  
 #changed to British spelling 
 group_armor_title: "Бронетанковые батальоны" #NT!
 HAS_ARMIES_WITH_OLD_TEMPLATE: "§RНевозможно удалить этот шаблон, поскольку $AMOUNT|H$ дивизий переходят с этого шаблона на новый (Ожидают получения оборудования, соответствующего новому шаблону).§!" #NT!
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC: "Развертывание должно иметь хотя бы один заказ на театре военных действий, который можно отнести к любой группе." #NT!
  
 #fixed missing article 
 CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§GClick§! чтобы указать место развертывания для этого развертывания.\n§GRight-click§! для сброса местоположения.\n§YЭто колониальный шаблон, который можно использовать только в стране происхождения!§!" #NT!
